create table TB_MENSAGENS (

    MENSAGENS_ATTB_MSG text,
    MENSAGENS_ATTB_ANEXOS text,
    MENSAGENS_ATTB_DE INTEGER not null,
    MENSAGENS_ATTB_PARA INTEGER not null,
    MENSAGENS_ATTB_ID integer not null primary key auto_increment

);


CREATE TABLE IF NOT EXISTS TB_MENSAGENS (
    MENSAGENS_ATTB_ID INT bigint NULL AUTO_INCREMENT PRIMARY KEY,
    MENSAGENS_ATTB_MSG TEXT,
    MENSAGENS_ATTB_ANEXOS TEXT,
    MENSAGENS_ATTB_DE bigint NOT NULL,
    MENSAGENS_ATTB_PARA bigint NOT NULL,
    FOREIGN KEY (MENSAGENS_ATTB_DE) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (MENSAGENS_ATTB_PARA) REFERENCES users (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
